### ISSUE TITLE
SAMD21 board support

### ISSUE THREAD

**Issue by newerbee** [SV-Zanshin/MCP7940#7]
Hi Zanshin,

Nice job with the library. But It looks like the library doesn't compile for SAMD21 based boards such as Arduino M0, or adafruit Feather M0. I am not an expert, but I happen to be using these boards, not sure what is wrong...

BR.
Newerbee

**Comment by SV-Zanshin** [comment]
Let me look into that. I don't have any of those boards, but can try to set my IDE to one of them and see what the problem might be.

**Comment by SV-Zanshin** [comment]
Sorry that this took so long to look into!

The reason was that the compiler settings were different and I was setting parameter defaults in the functions as well as in the prototype definitions. I've removed those from the function definitions and now the library compiles without a problem on SAMD21 boards.
